
import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Suitify',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}>
        <header className="w-full p-6 flex justify-between items-center border-b border-border">
          <h1 className="text-2xl font-semibold">
             <span className="bg-gradient-to-br from-gray-300 via-gray-500 to-gray-300 bg-clip-text text-transparent">Suit</span><span className="text-foreground">ify</span>
          </h1>
          <nav className="flex gap-4">
            <Link href="/">
              <Button variant="ghost">Home</Button>
            </Link>
            <Link href="/training">
              <Button variant="ghost">Creator Studio</Button>
            </Link>
            <Link href="/inference">
              <Button variant="ghost">Video Generator</Button>
            </Link>
          </nav>
        </header>
        <main className="p-8">
         {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
